# Frontend Web Dockerfile
FROM node:20-alpine AS builder
WORKDIR /web
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build:web

FROM nginx:1.25-alpine
COPY --from=builder /web/dist/apps/web /usr/share/nginx/html
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
